- name: Add filebeat key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: Add filebeat repository
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/oss-8.x/apt stable main
    state: present
    filename: elastic-8.x.list
  become: true

- name: install filebeat
  ansible.builtin.package:
    name:
      - filebeat
    state: present
  become: true