- name: update apt cache if debian
  ansible.builtin.apt:
    update_cache: yes
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: install essential packages
  ansible.builtin.package:
    name:
      - git
      - iotop
      - vim
      - nload
      - smartmontools
      - sysstat
      - qemu-guest-agent
      - pip
    state: present
  become: true

- name: start and enable sysstat
  ansible.builtin.systemd:
    name: sysstat
    state: started
    enabled: true
  become: true

- name: start and enable qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: true
  become: true
