- hosts: all
  roles:
    - essentials

- hosts: wazuh
  roles:
    - certbot

# - hosts: netbox
#   roles:
#     - essentials
#     - certbot
#     - netbox
#     - nginx

# - hosts: zabbix
#   roles:
#     # - essentials
#     # - certbot
#     - nginx
#     # - zabbix

# - hosts: wireguard
#   roles:
#     - essentials
#     # - wireguard

# - hosts: wireServer
#   roles:
#     - essentials

# - hosts: nextcloud
#   roles:
#     - certbot

