# - hosts: all
#   roles:
#     - essentials

# - hosts: wazuh
#   roles:
#     - certbot

- hosts: netbox
  roles:
    # - essentials
    - wazuh_agent
#     - certbot
#     - netbox
#     - nginx

- hosts: zabbix
  roles:
    - wazuh_agent
    # - essentials
    # - certbot
    # - nginx
    # - zabbix

- hosts: wireguard
  roles:
    - wazuh_agent
#     - essentials
#     # - wireguard

# - hosts: wireServer
#   roles:
#     - essentials

# - hosts: nextcloud
#   roles:
#     - certbot

