- hosts: main
  roles:
    - essentials

- hosts: netbox
  roles:
    - essentials
    # - certbot
    # - netbox

- hosts: graylog
  roles:
    - essentials
    # - certbot
    # - graylog

- hosts: zabbix
  roles:
    - essentials
    # - certbot
    # - nginx
    # - zabbix

- hosts: pihole
  roles:
    - essentials