- name: Add opensearch key
  ansible.builtin.apt_key:
    url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    state: present
  become: true

- name: Add opensearch repository
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main
    state: present
    filename: opensearch-2.x
  become: true

- name: install opensearch and java (for supporting scripts)
  ansible.builtin.package:
    name:
      - opensearch
      - default-jre
    state: present
  become: true

- name: change cluster name in conf
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'cluster.name'
    line: "cluster.name: {{ansible_hostname}}"
    state: present
  become: true

- name: change node name in conf
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'node.name'
    line: "node.name: {{ansible_hostname}}"
    state: present
  become: true

- name: change network host in conf
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'network.host'
    line: "network.host: 127.0.0.1"
    state: present
  become: true

- name: change discovery type for single node
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    insertafter: 'discovery.seed_hosts'
    line: "discovery.type: single-node"
    firstmatch: yes
    state: present
  become: true

- name: change do not auto create index
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    insertafter: 'action.destructive_requires_name'
    line: "action.auto_create_index: false"
    firstmatch: yes
    state: present
  become: true

# - name: change do not use default security index
#   ansible.builtin.lineinfile:
#     path: /etc/opensearch/opensearch.yml
#     search_string: 'allow_default_init_securityindex'
#     line: "plugins.security.allow_default_init_securityindex: false"
#     state: present
#   become: true

- name: change do not use demo certs
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'allow_unsafe_democertificates'
    line: "plugins.security.allow_unsafe_democertificates: false"
    state: present
  become: true

- name: change audit type
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'security.audit.type'
    line: "#plugins.security.audit.type: internal_opensearch"
    state: present
  become: true

- name: remove demo certs
  ansible.builtin.file:
    path: '/etc/opensearch/{{item}}'
    state: absent
  become: true
  loop:
    - root-ca.pem
    - esnode.pem
    - esnode-key.pem
    - kirk.pem
    - kirk-key.pem

# Assuming certbot is already installed, create opensearch certs
- name: check if a cert already exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/opensearch.kylegodinho.com/fullchain.pem
  register: pem_exists
  become: true

- name: run certbot command for opensearch certs
  ansible.builtin.command:
    cmd: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /home/{{ansible_user_id}}/.secrets/certbot/cloudflare.ini --non-interactive --agree-tos -m certbot@kylegodinho.com --dns-cloudflare-propagation-seconds 60 -d opensearch.kylegodinho.com
  become: true
  when: not pem_exists.stat.exists

- name: copy over script for setting up opensearch certs after renewal
  ansible.builtin.copy:
    src: opensearch_certs.sh
    dest: /etc/letsencrypt/renewal-hooks/post/opensearch_certs.sh
  become: true

- name: ensure script is executable
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/post/opensearch_certs.sh
    mode: '0755'
  become: true

- name: run cmd to convert privkey
  ansible.builtin.command:
    chdir: /etc/letsencrypt/live/opensearch.kylegodinho.com
    cmd: openssl pkcs8 -topk8 -nocrypt -in privkey.pem -out privkey-pkcs8.pem
  become: true

- name: Copy chain.pem to config folder
  ansible.builtin.copy:
    src: /etc/letsencrypt/live/opensearch.kylegodinho.com/chain.pem
    dest: /etc/opensearch/chain.pem
    remote_src: yes
  become: true

- name: Copy fullchain.pem to config folder
  ansible.builtin.copy:
    src: /etc/letsencrypt/live/opensearch.kylegodinho.com/fullchain.pem
    dest: /etc/opensearch/fullchain.pem
    remote_src: yes
  become: true

- name: Copy privkey-pkcs8.pem to config folder
  ansible.builtin.copy:
    src: /etc/letsencrypt/live/opensearch.kylegodinho.com/privkey-pkcs8.pem
    dest: /etc/opensearch/privkey-pkcs8.pem
    remote_src: yes
  become: true

- name: change transport ca cert
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'ssl.transport.pemtrustedcas_filepath'
    line: "plugins.security.ssl.transport.pemtrustedcas_filepath: chain.pem"
    state: present
  become: true

- name: change http ca cert
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'ssl.http.pemtrustedcas_filepath'
    line: "plugins.security.ssl.http.pemtrustedcas_filepath: chain.pem"
    state: present
  become: true

- name: change ssl cert
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'ssl.transport.pemcert_filepath'
    line: "plugins.security.ssl.transport.pemcert_filepath: fullchain.pem"
    state: present
  become: true

- name: change http cert
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'ssl.http.pemcert_filepath'
    line: "plugins.security.ssl.http.pemcert_filepath: fullchain.pem"
    state: present
  become: true

- name: change ssl key
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'ssl.transport.pemkey_filepath'
    line: "plugins.security.ssl.transport.pemkey_filepath: privkey-pkcs8.pem"
    state: present
  become: true

- name: change http key
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'ssl.http.pemkey_filepath'
    line: "plugins.security.ssl.http.pemkey_filepath: privkey-pkcs8.pem"
    state: present
  become: true

- name: change admin_dn
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch.yml
    search_string: 'CN=kirk'
    line: "  - CN=opensearch.kylegodinho.com"
    state: present
  become: true

# "-Xms{{(ansible_memory_mb.real.total // 1024) // 2}}g"
# Just manually setting to 2g for now
- name: change jvm heap size Xms
  ansible.builtin.lineinfile:
    path: /etc/opensearch/jvm.options
    search_string: 'Xms1g'
    line: "-Xms2g"
    state: present
  become: true

- name: change jvm heap size Xmx
  ansible.builtin.lineinfile:
    path: /etc/opensearch/jvm.options
    search_string: 'Xmx1g'
    line: "-Xmx2g"
    state: present
  become: true

- name: set kernel parameter per doc
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: true
    state: present
    reload: true
  become: true

- name: reload systemd start and enable opensearch
  ansible.builtin.systemd:
    name: opensearch
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: backup current security conf
  ansible.builtin.command:
    cmd: /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -backup ~/openbackup -icl -nhnv -cacert /etc/opensearch/chain.pem -cert /etc/opensearch/fullchain.pem -key /etc/opensearch/privkey-pkcs8.pem
  become: true

- name: copy over internal_users.yml
  ansible.builtin.copy:
    src: internal_users.yml
    dest: /etc/opensearch/opensearch-security/internal_users.yml
  become: true

- name: change admin pass
  ansible.builtin.lineinfile:
    path: /etc/opensearch/opensearch-security/internal_users.yml
    search_string: 'ADMIN_PASS_HASH'
    line: "  hash: \"{{lookup('community.general.bitwarden', 'OpensearchAdmin', field='hash')[0]}}\""
    state: present
  become: true

- name: apply new internal users
  ansible.builtin.command:
    cmd: /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -icl -nhnv -cacert /etc/opensearch/chain.pem -cert /etc/opensearch/fullchain.pem -key /etc/opensearch/privkey-pkcs8.pem -f /etc/opensearch/opensearch-security/internal_users.yml -t internalusers
  become: true

- name: restart opensearch
  ansible.builtin.systemd:
    name: opensearch
    state: restarted
  become: true