# rename cert and key to /etc/ssl/certs/netbox.crt and /etc/ssl/private/netbox.key
# or just change conf file to point to correct certs

#Certificate is saved at: /etc/letsencrypt/live/{{ansible_hostname}}.kylegodinho.com/fullchain.pem
#Key is saved at:         /etc/letsencrypt/live/{{ansible_hostname}}.kylegodinho.com/privkey.pem

- name: install nginx
  ansible.builtin.package:
    name:
      - nginx
    state: present
  become: true

- name: copy default nginx config
  ansible.builtin.copy:
    src: /opt/netbox/contrib/nginx.conf
    dest: /etc/nginx/sites-available/netbox
    remote_src: true
  become: true

- name: change server name in conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/netbox
    search_string: 'netbox.example.com'
    line: "    server_name {{ansible_hostname}}.kylegodinho.com;"
    state: present
  become: true

# set up cert/key in /etc/nginx/sites-available/netbox

- name: set cert in conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/netbox
    search_string: 'netbox.crt'
    line: "    ssl_certificate /etc/letsencrypt/live/{{ansible_hostname}}.kylegodinho.com/fullchain.pem;"
    state: present
  become: true

- name: set key in conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/netbox
    search_string: 'netbox.key'
    line: "    ssl_certificate_key /etc/letsencrypt/live/{{ansible_hostname}}.kylegodinho.com/privkey.pem;"
    state: present
  become: true

- name: remove default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: link netbox site conf to enabled sites
  ansible.builtin.file:
    src: /etc/nginx/sites-available/netbox
    dest: /etc/nginx/sites-enabled/netbox
    state: link
  become: true

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true
  become: true