- name: restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  become: true

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  become: true