# Certificate is saved at: /etc/letsencrypt/live/HOSTNAME.kylegodinho.com/fullchain.pem
# Key is saved at:         /etc/letsencrypt/live/HOSTNAME.kylegodinho.com/privkey.pem

- name: Install pexpect python package as become user for use when running certbot
  ansible.builtin.pip:
    name: pexpect
    state: present
  become: true

- name: install snap
  ansible.builtin.package:
    name:
      - snapd
    state: present
  become: true

- name: snap is started and enabled
  ansible.builtin.systemd:
    name: snapd.socket
    state: started
    enabled: true
  become: true

- name: install certbot plugin
  community.general.snap:
    name:
      - certbot
    classic: true
  become: true

- name: symlink certbot 
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  become: true

- name: plugin containment level set
  community.general.snap:
    name:
      - certbot
    options:
      - trust-plugin-with-root=ok
  become: true

- name: install cloudflare plugin
  community.general.snap:
    name:
      - certbot-dns-cloudflare
  become: true

- name: make directory for cloudflare.ini
  ansible.builtin.file:
    path: /home/{{ansible_user_id}}/.secrets/certbot
    state: directory

- name: create cloudflare.ini
  ansible.builtin.lineinfile:
    path: /home/{{ansible_user_id}}/.secrets/certbot/cloudflare.ini
    line: "dns_cloudflare_api_token = {{lookup('community.general.bitwarden', 'CloudflareAPI', field='token')[0]}}"
    create: true

- name: ensure good perms on cloudfare.ini
  ansible.builtin.file:
    path: //home/{{ansible_user_id}}/.secrets/certbot/cloudflare.ini
    mode: '600'

- name: check if a cert already exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ansible_hostname}}.kylegodinho.com/fullchain.pem
  register: pem_exists
  become: true

# - name: run certbot command
#   ansible.builtin.expect:
#     command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /home/{{ansible_user_id}}/.secrets/certbot/cloudflare.ini --register-unsafely-without-email --dns-cloudflare-propagation-seconds 60 -d {{ansible_hostname}}.kylegodinho.com
#     responses:
#       (?i)es: "Y"
#   become: true
#   when: not pem_exists.stat.exists

- name: run certbot command
  ansible.builtin.command:
    cmd: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /home/{{ansible_user_id}}/.secrets/certbot/cloudflare.ini --non-interactive --agree-tos -m certbot@kylegodinho.com --dns-cloudflare-propagation-seconds 60 -d {{ansible_hostname}}.kylegodinho.com
  become: true
  when: not pem_exists.stat.exists